[connections.my_database]
    type="sql"
    dialect="mysql"
    username="root"
    password="N0Password"
    host="127.0.0.1" # IP or URL
    port=3306 # Port number
    database="sampledata" # Database name
	
	